[project]
name = "honra-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai[google-genai,litellm]>=1.6.1",
    "ddgs>=9.16.0",
    "fastapi>=0.141.1",
    "ipykernel>=7.3.0",
    "langchain>=1.4.1",
    "langchain-core>=1.6.3",
    "langchain-google-genai>=4.4.0",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.2.11",
    "pydantic>=2.13.5",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "python-dotenv==1.2.3",
    "streamlit==1.63.0",
    "uvicorn>=0.52.4",
]
